import { test, expect } from '@playwright/test';

/**
 * Verify successful login with valid credentials
 *
 * Test Case ID: 1343
 * Priority: P0
 * Coverage: [object Object]
 * Steps:
   *   1. Enter valid username from Login dataset.
   *   2. Enter valid password from Login dataset.
   *   3. Click the Login button.
 * Expected Result: User is redirected to the dashboard.
 * Test Data: Valid username and password from Login dataset.
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://opensource-demo.orangehrmlive.com/
 */

test.describe('Verify successful login with valid credentials', () => {
  test('Verify successful login with valid credentials', async ({ page }) => {
  // @tc:TC1343
    await page.goto('https://opensource-demo.orangehrmlive.com/');
    await page.waitForLoadState('domcontentloaded');

    // Enter valid username from Login dataset.
    await page.locator('[name="username"]').fill(process.env.TEST_USERNAME ?? '');

    // Enter valid password from Login dataset.
    await page.locator('[name="password"]').fill(process.env.TEST_PASSWORD ?? '');

    // Click the Login button.
    await page.getByRole('link', { name: 'Submit Claim' }).click();
    await page.waitForLoadState('domcontentloaded');

    // ── Verify Expected Result ──
    await expect(page.getByRole('button', { name: '×' })).toBeVisible();
  });
});